# Load components from JSON file generated by Python script
#
# Usage:
#   1. Run Python script to generate images:
#      python scripts/generate_images.py --raw data.fif --ica ica.fif --output public/components/
#
#   2. Run Rails seed:
#      bin/rails db:seed
#
# The JSON file should be at public/components/components.json

require "json"

components_json_path = Rails.root.join("public", "components", "components.json")

if File.exist?(components_json_path)
  puts "Loading components from #{components_json_path}..."

  components = JSON.parse(File.read(components_json_path))

  components.each do |data|
    component = Component.find_or_initialize_by(
      ic_index: data["ic_index"],
      dataset: data["dataset"]
    )

    component.update!(
      image_path: data["image_path"],
      model_label: data["model_label"],
      model_confidence: data["model_confidence"]
    )
  end

  puts "Loaded #{components.size} components"
else
  puts "No components.json found at #{components_json_path}"
  puts "Run the Python image generator first:"
  puts "  python scripts/generate_images.py --raw data.fif --ica ica.fif --output public/components/"
end
